### ISSUE TITLE
[question] Public IP?

### ISSUE THREAD

**Issue by dashohoxha** [pparent76/Own-Mailbox_debian_install#1]
Does the Debian box need a public IP? Or it will work behind NAT as well?

What ports need to be open for it to work (besides 80/443)?

**Comment by pparent76** [comment]
It does not need a public IP or port opened. It works behind NAT.

Only an internet connection with DHCP, and that does not block tor is necessary, so that the Own-Mailbox can host tor hidden services.

Own-Mailbox has iptables to block everything but tor and the local network, so that there can be no data leak.

Pierre.

**Comment by dashohoxha** [comment]
> that will allow it to connect to the tor network and host tor hidden services

I am not familiar with tor and I don't know what are the requirements for it to work. Anyway I will just give it a try and see how well it works (and report any problems, if any).

**Comment by pparent76** [comment]
> I am not familiar with tor and I don't know what are the requirements for it to work.

Well except if you are living in china, or countries that filter internet, there is basically no requirement.

**Comment by dashohoxha** [comment]
No I don't live in China (fortunately, or unfortunately).
